export const PROJECTS = [
  {
    titleBox1: "Vodafone's B2B Platform",
    subTitleBox1: 'The key pain points identified by users played a pivotal role in shaping the project’s development:',
    bgImageMobileBox1: 'url(../assets/images/Card1.jpg)',
    bgImageTabletBox1: 'url(../assets/images/Card1.jpg)',
    bgImageLaptopBox1: 'url(../assets/images/Card1.jpg)',
    bgImageDesktopBox1: 'url(../assets/images/Card1.jpg)',
    imgButtonBox1: './assets/images/Arrow.svg',

    titleBox2: 'Endesa',
    subTitleBox2: 'The key pain points identified by users played a pivotal role in shaping the project’s development:',
    bgImageMobileBox2: 'url(../assets/images/Card2.jpg)',
    bgImageTabletBox2: 'url(../assets/images/Card2.jpg)',
    bgImageLaptopBox2: 'url(../assets/images/Card2.jpg)',
    bgImageDesktopBox2: 'url(../assets/images/Card2.jpg)',
    imgButtonBox2: './assets/images/Arrow.svg',
    reverse: false
  },
  {
    titleBox1: 'New Project',
    subTitleBox1: 'The key pain points identified by users played a pivotal role in shaping the project’s development:',
    bgImageMobileBox1: 'url(../assets/images/Card1.jpg)',
    bgImageTabletBox1: 'url(../assets/images/Card1.jpg)',
    bgImageLaptopBox1: 'url(../assets/images/Card1.jpg)',
    bgImageDesktopBox1: 'url(../assets/images/Card1.jpg)',
    imgButtonBox1: './assets/images/Arrow.svg',
    titleBox2: 'New Project',
    subTitleBox2: 'The key pain points identified by users played a pivotal role in shaping the project’s development:',
    bgImageMobileBox2: 'url(../assets/images/Card1.jpg)',
    bgImageTabletBox2: 'url(../assets/images/Card1.jpg)',
    bgImageLaptopBox2: 'url(../assets/images/Card1.jpg)',
    bgImageDesktopBox2: 'url(../assets/images/Card1.jpg)',
    imgButtonBox2: './assets/images/Arrow.svg',
    reverse: true
  }
  // {
  //   titleBox1: 'New Project',
  //   subTitleBox1: 'The key pain points identified by users played a pivotal role in shaping the project’s development:',
  //   bgImageMobileBox1: 'url(../assets/images/Card1.jpg)',
  //   bgImageTabletBox1: 'url(../assets/images/Card1.jpg)',
  //   bgImageLaptopBox1: 'url(../assets/images/Card1.jpg)',
  //   bgImageDesktopBox1: 'url(../assets/images/Card1.jpg)',
  //   imgButtonBox1: './assets/images/Arrow.svg',
  //   titleBox2: 'New Project',
  //   subTitleBox2: 'The key pain points identified by users played a pivotal role in shaping the project’s development:',
  //   bgImageMobileBox2: 'url(../assets/images/Card1.jpg)',
  //   bgImageTabletBox2: 'url(../assets/images/Card1.jpg)',
  //   bgImageLaptopBox2: 'url(../assets/images/Card1.jpg)',
  //   bgImageDesktopBox2: 'url(../assets/images/Card1.jpg)',
  //   imgButtonBox2: './assets/images/Arrow.svg',
  //   reverse: false
  // },
  // {
  //   titleBox1: 'New Project',
  //   subTitleBox1: 'The key pain points identified by users played a pivotal role in shaping the project’s development:',
  //   bgImageMobileBox1: 'url(../assets/images/Card1.jpg)',
  //   bgImageTabletBox1: 'url(../assets/images/Card1.jpg)',
  //   bgImageLaptopBox1: 'url(../assets/images/Card1.jpg)',
  //   bgImageDesktopBox1: 'url(../assets/images/Card1.jpg)',
  //   imgButtonBox1: './assets/images/Arrow.svg',
  //   titleBox2: 'New Project',
  //   subTitleBox2: 'The key pain points identified by users played a pivotal role in shaping the project’s development:',
  //   bgImageMobileBox2: 'url(../assets/images/Card1.jpg)',
  //   bgImageTabletBox2: 'url(../assets/images/Card1.jpg)',
  //   bgImageLaptopBox2: 'url(../assets/images/Card1.jpg)',
  //   bgImageDesktopBox2: 'url(../assets/images/Card1.jpg)',
  //   imgButtonBox2: './assets/images/Arrow.svg',
  //   reverse: true
  // }
];
